In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('air_quality_northern.csv', index_col=0, parse_dates=True)
df = df.rename(columns={'วันที่': 'date'})
df['date'] = pd.to_datetime(df['date'])

/var/folders/vg/p01w91952dv7q8gqp503xbk80000gn/T/ipykernel_95629/659772072.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('air_quality_northern.csv', index_col=0, parse_dates=True)

In [4]:
daily_mean = df.groupby(df['date'].dt.date)[['73t', '41t', '75t', '58t', '39t', '76t']].mean()
daily_mean

,73t,41t,75t,58t,39t,76t
date,,,,,,
2025-03-31,98.116667,27.220833,114.170833,258.900000,55.925000,61.808333
2025-04-01,67.416667,34.825000,92.787500,184.100000,46.600000,44.941667
2025-04-02,71.383333,34.262500,126.966667,243.879167,44.862500,40.033333
2025-04-03,76.870833,57.187500,103.495833,289.820833,50.329167,28.373913
2025-04-04,77.683333,57.579167,91.120833,204.825000,49.058333,33.029167
2025-04-05,81.170833,29.695833,84.104762,165.379167,38.050000,23.154167
2025-04-06,80.745833,33.533333,56.025000,114.325000,25.045833,31.220833
2025-04-07,61.795833,29.687500,35.908333,65.337500,24.458333,23.458333
2025-04-08,68.975000,37.816667,47.770833,43.362500,22.633333,24.945833
2025-04-09,114.137500,37.445833,76.283333,80.250000,27.887500,29.270833
2025-04-10,120.462500,30.855000,63.045833,97.095833,38.033333,32.891667
2025-04-11,91.487500,25.000000,57.675000,76.818182,30.125000,21.370833
2025-04-12,67.408333,18.608333,42.250000,19.425000,15.283333,14.075000
2025-04-13,26.262500,13.879167,44.525000,24.183333,12.266667,13.445833
2025-04-14,15.187500,14.854167,23.129167,14.125000,9.170833,9.633333
2025-04-15,15.087500,17.683333,23.491667,7.904167,10.666667,11.737500
2025-04-16,15.129167,16.562500,23.908333,14.716667,11.716667,12.212500
2025-04-17,16.508333,14.241667,25.466667,12.858333,11.533333,11.950000
2025-04-18,18.262500,12.270833,24.420833,11.645833,10.687500,11.362500
2025-04-19,21.191667,13.504167,24.629167,20.816667,13.354167,13.345833
2025-04-20,25.729167,14.858333,26.991667,41.925000,13.004167,14.716667
2025-04-21,27.316667,16.458333,25.278261,45.658333,19.912500,14.383333
2025-04-22,44.617391,20.129167,37.725000,43.600000,19.645833,19.579167
2025-04-23,40.516667,22.083333,46.833333,34.591667,28.937500,20.770833
2025-04-24,60.283333,26.941667,45.650000,39.775000,32.970833,25.820833
2025-04-25,65.333333,29.708333,50.280000,37.662500,39.841667,29.745833
2025-04-26,84.870833,24.700000,58.504167,58.725000,34.245833,25.795833
2025-04-27,56.016667,19.054167,57.883333,41.245833,31.583333,20.200000
2025-04-28,30.029167,24.179167,40.383333,30.379167,16.504167,25.004167
2025-04-29,21.204762,16.485714,37.885000,14.304762,18.214286,16.857143

In [5]:
daily_mean.to_csv('dataset/PM2.5/1m_history_PM25.csv', index=True)